server:
  http:
    listen_addr: ":9090" # Chproxy будет слушать на 9090 порту

users:
  - name: "default"
    to_user: "default"
    to_cluster: "cluster1"

clusters:
  - name: "cluster1"
    nodes: ["ch1:8123", "ch3:8123"]

hack_me_please: true

